/**
 * The doc tests (docs/REVIEW.md §8.2, layer L3). This script finds each code block with the meta word `doctest`
 * in the docs, and writes one test file for each block to `.doctest/`. Then `tsc` checks the types of the files,
 * and Vitest runs them.
 *
 * The rules for the lines of a block:
 * - `import` lines go to the top of the file. Other names come from `src/lib/doctest-prelude.ts`.
 * - `expr; // => value` becomes `expect(expr).toEqual(value)`. With `...` in the value, it becomes `toMatchObject`.
 * - `expr; // : Type` becomes `expectTypeOf(expr).toEqualTypeOf<Type>()`.
 * - A line with the comment `// type error` gets `@ts-expect-error`, so the type check fails if the line compiles.
 */
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import * as prelude from "../src/lib/doctest-prelude.ts";

const site = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repo = resolve(site, "../..");
const out = join(site, ".doctest");

const walk = (dir: string): string[] =>
  readdirSync(dir, { withFileTypes: true }).flatMap((d) => (d.isDirectory() ? walk(join(dir, d.name)) : [join(dir, d.name)]));

const sources = [
  join(repo, "README.md"),
  join(repo, "spec/README.md"),
  ...readdirSync(join(repo, "packages")).map((p) => join(repo, "packages", p, "README.md")),
  ...walk(join(site, "src/content/docs")).filter((f) => /\.mdx?$/.test(f)),
].filter((f) => {
  try {
    readFileSync(f);
    return true;
  } catch {
    return false;
  }
});

interface Block {
  readonly file: string;
  readonly line: number;
  readonly body: readonly string[];
}

const blocks: Block[] = [];
for (const file of sources) {
  const lines = readFileSync(file, "utf8").split(/\r?\n/);
  for (let i = 0; i < lines.length; i++) {
    if (!/^```(ts|tsx|typescript)\b.*\bdoctest\b/.test(lines[i] ?? "")) continue;
    const body: string[] = [];
    let j = i + 1;
    for (; j < lines.length && !(lines[j] ?? "").startsWith("```"); j++) body.push(lines[j] ?? "");
    blocks.push({ file, line: i + 1, body });
    i = j;
  }
}

const preludeNames = new Set(Object.keys(prelude));
const TYPE_WORDS = new Set(["boolean", "number", "string", "unknown", "never", "readonly", "undefined", "null", "true", "false"]);
const stripStringsAndComments = (code: string): string =>
  code.replace(/\/\/.*$/gm, "").replace(/"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'|`(?:[^`\\]|\\.)*`/g, '""');
const identifiers = (code: string): Set<string> => new Set(stripStringsAndComments(code).match(/(?<![.\w$])[A-Za-z_$][\w$]*/g) ?? []);

function transform(body: readonly string[]): { readonly imports: string[]; readonly code: string[]; readonly typeNames: Set<string> } {
  const imports: string[] = [];
  const code: string[] = [];
  const typeNames = new Set<string>();
  for (const line of body) {
    if (/^\s*import\s/.test(line)) {
      imports.push(line);
      continue;
    }
    const value = /^(\s*)(.+?);?\s*\/\/ => (.+)$/.exec(line);
    if (value !== null) {
      const [, indent, expr, expected] = value as unknown as [string, string, string, string];
      const partial = expected.includes("...");
      const shape = expected.replace(/,\s*\.\.\./g, "").replace(/\.\.\.\s*,?/g, "");
      code.push(`${indent}expect(${expr}).${partial ? "toMatchObject" : "toEqual"}(${shape});`);
      continue;
    }
    const type = /^(\s*)(.+?);?\s*\/\/ : (.+)$/.exec(line);
    if (type !== null) {
      const [, indent, expr, t] = type as unknown as [string, string, string, string];
      for (const n of identifiers(t)) if (!TYPE_WORDS.has(n)) typeNames.add(n);
      code.push(`${indent}expectTypeOf(${expr}).toEqualTypeOf<${t}>();`);
      continue;
    }
    if (/\/\/ type error/.test(line)) code.push(`${/^\s*/.exec(line)?.[0] ?? ""}// @ts-expect-error -- the doc says that this line has a type error`);
    code.push(line);
  }
  return { imports, code, typeNames };
}

rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });
const preludePath = "../src/lib/doctest-prelude.ts";
for (const b of blocks) {
  const { imports, code, typeNames } = transform(b.body);
  const imported = identifiers(imports.join("\n"));
  const used = [...identifiers(code.join("\n"))].filter((n) => preludeNames.has(n) && !imported.has(n)).toSorted();
  const types = [...typeNames].filter((n) => !imported.has(n) && !used.includes(n)).toSorted();
  const rel = relative(repo, b.file).replaceAll("\\", "/");
  const name = `${rel.replace(/^packages\/site\/src\/content\/docs\//, "site/").replace(/[^\w]+/g, "-")}-L${b.line}`;
  const text = [
    `// Generated by scripts/doctest.ts from ${rel}, line ${b.line}. Do not edit.`,
    `import { expect, expectTypeOf, it } from "vitest";`,
    ...imports,
    ...(used.length > 0 ? [`import { ${used.join(", ")} } from "${preludePath}";`] : []),
    ...(types.length > 0 ? [`import type { ${types.join(", ")} } from "${preludePath}";`] : []),
    "",
    `it(${JSON.stringify(`${rel}:${b.line}`)}, () => {`,
    ...code.map((l) => (l === "" ? "" : `  ${l}`)),
    `});`,
    "",
  ].join("\n");
  writeFileSync(join(out, `${name}.test.ts`), text);
}
console.info(`doctest: ${blocks.length} blocks from ${new Set(blocks.map((b) => b.file)).size} files`);
